=== codehack9991/MOA-1.0/config/sim/simrules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<element name="rules">
		<complexType mixed="true">
			<sequence>
				<element name="rule" minOccurs='0' maxOccurs='unbounded'>
					<complexType mixed="true">
						<sequence>
							<element name="filter" minOccurs='0' maxOccurs='1'></element>
							<element name="validate" minOccurs='0' maxOccurs='1'></element>
							<element name="responses" minOccurs='0' maxOccurs='1'>
								<complexType mixed="true">
									<sequence>
										<element name="response" minOccurs='0' maxOccurs='unbounded'>
											<complexType mixed="true">
												<attribute name="delay" type="integer" use="optional"
													default="0"></attribute>
												<attribute name="id" type="string" use="optional" default=""></attribute>
												<attribute name="removetags" type="string" use="optional" default=""></attribute>
												<attribute name="saveas" type="string" use="optional" default=""></attribute>
												<attribute name="refer" type="string" use="optional" default=""></attribute>
												<attribute name="exectype" use="required">
													<annotation>
														<documentation>Possible values are ACK, FILL, REJECT, DFD,
															CUSTOM, CANCEL, BURST
														</documentation>
													</annotation>
													<simpleType>
														<restriction base="string">
															<enumeration value="ACK"></enumeration>
															<enumeration value="FILL"></enumeration>
															<enumeration value="CANCEL"></enumeration>
															<enumeration value="REJECT"></enumeration>
															<enumeration value="DFD"></enumeration>
															<enumeration value="BUST"></enumeration>
															<enumeration value="CUSTOM"></enumeration>
															<enumeration value="SAVED"></enumeration>
														</restriction>
													</simpleType>

												</attribute>
												<attribute name="condition" type="string" use="optional"
													default="true">
													<annotation>
														<documentation>

															If condition tag is present it will
															evaluate the condition
															and if true the response would be
															sent, Use Java Equality, Relational, and Conditional
															Operators

														</documentation>
													</annotation>
												</attribute>
											</complexType>
										</element>
									</sequence>

								</complexType>
							</element>
						</sequence>
						<attribute name="name" use="required"></attribute>
						<attribute name="active" use="optional" default="true"
							type="boolean">
						</attribute>
					</complexType>
				</element>
			</sequence>
			<attribute name="delimiter" use="required"></attribute>

		</complexType>

	</element>
</schema>

=== codehack9991/MOA-1.0/config/sim/simrules.xml
<?xml version="1.0" encoding="UTF-8"?>
<rules  delimiter=","
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="simrules.xsd">


    <rule name="Fill cancel crossover8_1" active="true">
        <filter>35=D,48=DE0005772206</filter>
        <responses>
            <response exectype="ACK">39=0,150=0</response>
        </responses>
    </rule>
    <rule name="Fill cancel crossover8_2" active="true">
        <filter>35=G,48=DE0005772206</filter>
        <responses>
            <response exectype="ACK" saveas="ack811">39=5, 150=5</response>
        </responses>
    </rule>
    <rule name="Fill cancel crossover8_3" active="true">
        <filter>35=F,48=DE0005772206</filter>
        <responses>
            <response exectype="SAVED" refer="ack811"></response>
            <response exectype="CANCEL">1815=5,25108=0,30060=1495630105380925193</response>
        </responses>
    </rule> 
    <rule name="Fill cancel crossover8_3" active="true">
        <filter>35=D,48=DE0005772207</filter>
        <responses>
            <response exectype="FILL" removetags="6">38={38}/2</response>
            <response exectype="ACK"/>
        </responses>
    </rule> 
</rules>
